title: LegionOS Blog
author: 
subtitle: The life of a frustrated engineer

url: "https://blog.legionos.org"
baseurl: ""

footer_only_homepage: true
footer_url: "#"
footer_text: "Copyright 2021 LegionOS"

profile-picture: assets/profile.png
favicon_location: assets/logo.png

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile ]

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

navbar:
 - name: "features"
   link: "features"
 - name: "Main"
   absolute-link: "https://legionos.org"
   
  # Disqus (Set to your disqus id)
disqus: legionos
